function f=sk(u,g)
global ipx imx ipz imz dx dz;

f=((u(ipx,:,1)+u(:,:,1)).*g(ipx,:)/(4*dx)...
  -(u(imx,:,1)+u(:,:,1)).*g(imx,:)/(4*dx)...
  +(u(:,ipz,2)+u(:,:,2)).*g(:,ipz)/(4*dz)...
  -(u(:,imz,2)+u(:,:,2)).*g(:,imz)/(4*dz) );
